## Introducción a la Inteligencia Artificial
## Carrera de Especialización en Inteligencia Artificial


---


# *Resolución de trabajos prácticos*

# Mariano A. de Luzuriaga



In [72]:
import numpy as np

In [125]:
# ejercicio 1
matriz = np.array([[1, 1, 1],[5, 0, 3],[0, 1, 1]])


def norma_l0(m):
    not_zero = lambda x : 1 if x else 0
    return np.sum(np.any(m), axis=1)

def norma_lp(m, p):
    if p == 0:
        raise Exception("El valor de p debe ser mayor a 0")
    return np.sum(np.abs(m)**p, axis=1)**(1/p)


def norma_linf(m):
    return np.max(m, axis=1)

#print(f'l0: {norma_l0(matriz)}')
print(f'l1: {norma_lp(matriz, 1)}')
print(f'l2: {norma_lp(matriz, 2)}')
print(f'linf: {norma_linf(matriz)}')

l1: [3. 8. 2.]
l2: [1.73205081 5.83095189 1.41421356]
linf: [1 5 1]


In [74]:
# ejercicio 2
matriz = np.array([[2, 7, 3],[2, 11, 17],[1, 2, 1]])


def ordenar_por_normas(m):
    norms = norma_lp(m, 2)
    indices =  np.argsort(norms)[::-1]
    print(indices)
    return m.take(indices, axis=0)
    
    
print(f'Matriz \n {matriz} \n ordenada por normas de sus filas -> \n {ordenar_por_normas(matriz)}')

[1 0 2]
Matriz 
 [[ 2  7  3]
 [ 2 11 17]
 [ 1  2  1]] 
 ordenada por normas de sus filas -> 
 [[ 2 11 17]
 [ 2  7  3]
 [ 1  2  1]]


In [75]:
# ejercicio 3


In [115]:
# ejercicio 4

truth = np.array([1,1,0,1,1,1,0,0,0,1], dtype=int)
prediction = np.array([1,1,1,1,0,0,1,1,0,0], dtype=int)



tp = np.sum((truth==1) & (prediction==1))
fp = np.sum((truth==0) & (prediction==1))
tn = np.sum((truth==0) & (prediction==0))
fn = np.sum((truth==1) & (prediction==0))

precision = tp / (tp + fp)
recall = tp / (tp + fn)
accuracy = (tp + tn) / (tp + tn + fp +fn)

print(f'Precision: {precision} \nRecall: {recall} \nAccuracy: {accuracy}')


Precision: 0.5 
Recall: 0.5 
Accuracy: 0.4


In [116]:
# ejercicio 5
q_id = np.array([1, 1, 1, 1, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4])         
predicted_rank = np.array([0, 1, 2, 3, 0, 1, 2, 0, 1, 2, 3, 4, 0, 1, 2, 3])  
truth_relevance = np.array([True, False, True, False, True, True, True, False, False, False, False,True, False, False, True]) 



TypeError: _argpartition_dispatcher() missing 1 required positional argument: 'kth'

In [129]:
# ejercicio 6

X = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
C = np.array([[1, 0, 0], [0, 1, 1]])

X1 = norma_lp(X - C[0], 2)
X2 = norma_lp(X - C[1], 2)

print(f'Distancia de X respecto centroide {C[0]}: {X1}')
print(f'Distancia de X respecto centroide {C[1]}: {X2}')

Distancia de X respecto centroide [1 0 0]: [ 3.60555128  8.36660027 13.45362405]
Distancia de X respecto centroide [0 1 1]: [ 2.44948974  7.54983444 12.72792206]


In [131]:
#ejercicio 7

distancias = np.array([X1, X2])
a = np.argmin(distancias, axis=0)
a



array([1, 1, 1])

In [161]:
# ejercicio 8

dim = 3
samples = 1000
N = 3*1000
X = np.random.normal(size=N).reshape(n, dim)

centroids_number = 5
rng = np.random.default_rng(12345)
centroids_idx = rng.integers(low=0, high=samples, size=centroids_number)
centroids = np.take(X, centroids_idx, axis=0)
centroids

array([[-0.57010393, -1.1356111 , -1.22049753],
       [ 0.98663849,  1.11380644, -0.03842829],
       [-0.25363107,  1.62164053, -0.43329515],
       [ 0.39080184, -0.56725851,  1.29305127],
       [-1.67482094, -0.04802034,  0.96541788]])

array([ 0,  2,  2,  6,  7,  8,  8,  9,  9, 11, 12, 12, 13, 15, 18, 19, 20,
       21, 21, 22, 22, 22, 24, 25, 25, 25, 26, 26, 27, 29, 31, 31, 32, 33,
       33, 33, 33, 34, 35, 39, 39, 44, 45, 45, 46, 47, 47, 47, 49, 49, 54,
       54, 55, 55, 56, 56, 59, 59, 60, 61, 62, 62, 63, 64, 64, 65, 66, 66,
       67, 67, 68, 69, 69, 70, 70, 71, 72, 73, 73, 73, 74, 77, 78, 79, 80,
       81, 83, 83, 85, 86, 88, 89, 90, 91, 92, 93, 93, 94, 94, 98])